name = "reson-api-worker"
main = "index.js"
compatibility_date = "2026-04-02"

[[r2_buckets]]
binding = "MUSIC_BUCKET"
bucket_name = "local-music-bucket"
preview_bucket_name = "local-music-bucket"

[[kv_namespaces]]
binding = "SESSIONS"
id = "local_sessions"

[[kv_namespaces]]
binding = "REQUESTS"
id = "local_requests"
[vars]
RESEND_API_KEY = "e_au7cbMUs_JQkF9m7XxBcjmv2oU6V9Bru6"
OWNER_EMAIL = "jacetbaum@gmail.com"